/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.io.File;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.text.DecimalFormat;
import java.util.logging.Level;


/**
 *
 * @author M S I
 */
public class frameproj extends javax.swing.JFrame {

    public frameproj() throws SQLException {
        initComponents();
        Projk.ConfigDB();
        
        load_table();

        tjml.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                textChanged();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                textChanged();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                textChanged();
 
            }
            public void textChanged() {
                Integer valHar = Integer.parseInt(tharga.getText()) * Integer.parseInt(tjml.getText());
                DecimalFormat format = new DecimalFormat("0.#");
                
                if (tjml.getText().isEmpty()) {
                    tbiaya.setText("");
                    tdiskon.setText("");
                    ttotal.setText("");
                    return;
                }
                   
                tbiaya.setText(valHar.toString());
                tharga.setText(valHar.toString());
                if (Integer.parseInt(tjml.getText()) >= 5 && Integer.parseInt(tjml.getText()) <= 10) {
                    Double val = Double.parseDouble(tbiaya.getText()) * 0.05;
                    Integer valTotal = valHar - val.intValue();
                    
                    tdiskon.setText(format.format(val));
                    ttotal.setText(valTotal.toString());
                } else if (Integer.parseInt(tjml.getText()) > 10) {
                    Double val = Double.parseDouble(tbiaya.getText()) * 0.10;
                    Integer valTotal = valHar - val.intValue();

                    tdiskon.setText(format.format(val));
                    ttotal.setText(valTotal.toString());
                } else {
                    Integer valTotal = valHar;
                    
                    tdiskon.setText("0");
                    ttotal.setText(valTotal.toString());
                }
            }
        });

    }

    void setResult() {
    try {
      String tharga = tbiaya.getText();

      long rJumlahPaket = Long.parseLong(tjml.getText());
      long hargaPerPaket = 15000;
      long totalHarga;

      if (rJumlahPaket >= 5 && rJumlahPaket <= 10) {
          totalHarga = rJumlahPaket * hargaPerPaket * 95 / 100; // Diskon 5%
      } else if (rJumlahPaket > 10) {
          totalHarga = rJumlahPaket * hargaPerPaket * 90 / 100; // Diskon 10%
      } else {
          totalHarga = rJumlahPaket * hargaPerPaket;
      }

      tjml.setText(String.valueOf(totalHarga));
      ttotal.setText("Rp. " + totalHarga);
      tdiskon.setText(""); // Tidak ada bonus yang diberikan
    } catch (NumberFormatException e) {
      tjml.setText("");
      ttotal.setText("Rp. 0");
      tdiskon.setText("");
    }

  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cjenis = new javax.swing.JComboBox<>();
        tkode = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        tbiaya = new javax.swing.JTextField();
        Diskon = new javax.swing.JLabel();
        tdiskon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ttotal = new javax.swing.JTextField();
        bhapus = new javax.swing.JButton();
        bexit = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        btambah = new javax.swing.JButton();
        bbaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        bcetak = new javax.swing.JButton();
        tjml = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tharga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SISTEM ADMINISTRASI PENGIRIMAN PAKET");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Kode Paket");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Pengirim");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Berat Paket");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Pengiriman");

        cjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Cargo", "Instan", " " }));
        cjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjenisActionPerformed(evt);
            }
        });

        tkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodeActionPerformed(evt);
            }
        });

        tbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbiayaActionPerformed(evt);
            }
        });

        Diskon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Diskon.setText("Diskon");

        tdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdiskonActionPerformed(evt);
            }
        });

        jLabel8.setText("====================================");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total Biaya");

        ttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotalActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 51, 51));
        bhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bexit.setBackground(new java.awt.Color(153, 153, 153));
        bexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        bedit.setBackground(new java.awt.Color(255, 255, 51));
        bedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        btambah.setBackground(new java.awt.Color(51, 255, 0));
        btambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btambah.setText("TAMBAH");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bbaru.setBackground(new java.awt.Color(0, 102, 255));
        bbaru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbaru.setText("BARU");
        bbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbaruActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Paket", "Nama Pengirim", "Jumlah Paket", "Jenis Pengiriman", "Biaya Admin", "PPN", "Diskon", "Total Biaya"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Biaya Pengiriman");

        bcetak.setBackground(new java.awt.Color(0, 255, 204));
        bcetak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bcetak.setText("CETAK");
        bcetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcetakMouseClicked(evt);
            }
        });
        bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcetakActionPerformed(evt);
            }
        });

        tjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjmlActionPerformed(evt);
            }
        });
        tjml.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tjmlPropertyChange(evt);
            }
        });
        tjml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tjmlKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Alamat Penerima");

        tharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thargaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Harga Paket /Kg");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PT. BERKAH PENGIRIMAN MAJU JAYA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Diskon)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel12))
                            .addComponent(jLabel13))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(talamat)
                            .addComponent(tnama)
                            .addComponent(tkode)
                            .addComponent(cjenis, 0, 132, Short.MAX_VALUE)
                            .addComponent(tjml)
                            .addComponent(tdiskon)
                            .addComponent(tbiaya)
                            .addComponent(tharga)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bbaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bedit)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(16, 16, 16)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bexit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bcetak))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(cjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Diskon)
                            .addComponent(tdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(922, 922, 922))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
    try {
             try {
                 String sql = "INSERT INTO admin (kd_paket, nama_pengirim, alamat, jns_pengiriman, harga, jml_paket, biaya, diskon, total) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                 java.sql.Connection conn=(java.sql.Connection)Projk.ConfigDB();
                 try (java.sql.PreparedStatement pst=conn.prepareStatement(sql)){                
                         pst.setString(1, tkode.getText());
                         pst.setString(2, tnama.getText());
                         pst.setString(3, talamat.getText());
                         pst.setString(4, (String)cjenis.getSelectedItem());
                         pst.setString(5, tharga.getText());
                         pst.setString(6, tjml.getText());
                         pst.setString(7, tbiaya.getText());
                         pst.setString(8, tdiskon.getText());
                         pst.setString(9, ttotal.getText());
                         pst.executeUpdate();
                 }
                 JOptionPane.showMessageDialog(null,"Penyimpanan Data Berhasil");
             } catch (SQLException | HeadlessException e) {
                 JOptionPane.showMessageDialog(this, e.getMessage());
             } 
         load_table();
         kosong();
        } catch (HeadlessException ex) {
             Logger.getLogger(Projk.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
             Logger.getLogger(Projk.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btambahActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {
            // Assuming the first column is the NIM
            String kd_paket = tbl.getValueAt(selectedRow, 0).toString();

            try {
                String sql = "DELETE FROM admin WHERE kd_paket = ?";
                java.sql.Connection conn = (java.sql.Connection) Projk.ConfigDB();
                try (java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setString(1, kd_paket);
                    pstmt.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                load_table(); // Refresh the table
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus");
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void tbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbiayaActionPerformed

    private void tkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodeActionPerformed

    private void tdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdiskonActionPerformed

    private void bbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbaruActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_bbaruActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "UPDATE admin SET nama_pengirim=?, alamat=?, jns_pengiriman=?, harga=?, jml_paket=?, biaya=?, diskon=?, total=? WHERE kd_paket=?";
            java.sql.Connection conn = Projk.db;
            try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1, tnama.getText());
                pst.setString(2, talamat.getText());
                pst.setString(3, (String) cjenis.getSelectedItem());
                pst.setString(4, tharga.getText());
                pst.setString(5, tjml.getText());
                pst.setString(6, tbiaya.getText());
                pst.setString(7, tdiskon.getText());
                pst.setString(8, ttotal.getText());
                pst.setString(9, tkode.getText());
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil dirubah");
            }
            load_table();
            kosong();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Merubah Data Gagal: " + e.getMessage());
        }

    }//GEN-LAST:event_beditActionPerformed

    private void tjmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjmlKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tjmlKeyTyped

    private void tjmlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tjmlPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tjmlPropertyChange

    private void ttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotalActionPerformed

    private void bcetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcetakMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bcetakMouseClicked

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int baris = tbl.rowAtPoint(evt.getPoint());
        
        String id = tbl.getValueAt(baris, 0).toString();
        tkode.setText(id);
        
        String name = tbl.getValueAt(baris, 1).toString();
        tnama.setText(name);
        
        String alamat = tbl.getValueAt(baris, 2).toString();
        talamat.setText(alamat);
        
        String jenis = tbl.getValueAt(baris, 3).toString();
        cjenis.setSelectedItem(jenis);
        
        String harga = tbl.getValueAt(baris, 4).toString();
        tharga.setText(harga);
        
        String jml_paket = tbl.getValueAt(baris, 5).toString();
        tjml.setText(jml_paket);
        
        String biaya = tbl.getValueAt(baris, 6).toString();
        tbiaya.setText(biaya);
        
        String diskon = tbl.getValueAt(baris, 7).toString();
        tdiskon.setText(diskon);
        
        String total = tbl.getValueAt(baris, 8).toString();
        ttotal.setText(total);
    }//GEN-LAST:event_tblMouseClicked

    private void cjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjenisActionPerformed
        String jpaket = String.valueOf(cjenis.getSelectedItem());

        if (jpaket.equals("Reguler")) {
            tharga.setText("10000");
        } else if (jpaket.equals("Cargo")) {
            tharga.setText("15000");
        } else if (jpaket.equals("Instan")) {
            tharga.setText("20000");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cjenisActionPerformed

    private void tjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjmlActionPerformed

    private void bcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcetakActionPerformed
        try {
            String report = new File("D:\\java\\projk\\src\\projk\\report.jasper").getPath();
            JasperPrint jp = JasperFillManager.fillReport(report, null, Projk.db);
            JasperViewer.viewReport(jp);
        } catch (JRException e) {
            Logger.getLogger(e.getMessage()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_bcetakActionPerformed

    private void thargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameproj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameproj().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameproj.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diskon;
    private javax.swing.JButton bbaru;
    private javax.swing.JButton bcetak;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton btambah;
    private javax.swing.JComboBox<String> cjenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField tbiaya;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tdiskon;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tjml;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField ttotal;
    // End of variables declaration//GEN-END:variables

    private void load_table() throws SQLException {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Paket");
        model.addColumn("Nama Pengirim");
        model.addColumn("Alamat");
        model.addColumn("Jenis Pengirim");
        model.addColumn("Harga Satuan");
        model.addColumn("Jumlah Paket");
        model.addColumn("Biaya Pengiriman");
        model.addColumn("Diskon");
        model.addColumn("Total");


        int no = 1;
        String sql = "SELECT * FROM admin";
        
        Connection conn = (java.sql.Connection) Projk.ConfigDB();
        ResultSet res = conn.createStatement().executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("kd_paket"), 
                res.getString("nama_pengirim"), 
                res.getString("alamat"), 
                res.getString("jns_pengiriman"), 
                res.getString("harga"), 
                res.getString("jml_paket"),
                res.getString("biaya"),  
                res.getString("diskon"), 
                res.getString("total")
            });
        }

        tbl.setModel(model);
        
    
    }

    private boolean validation() {
        String kd_paket = tkode.getText();
        String nama_pengiriman = tnama.getText();
        String alamat = talamat.getText();
        String jenis = cjenis.getName();
        String harga = tharga.getText();
        String jml_paket = tjml.getText();
        String biaya = tbiaya.getText();
        String diskon = tdiskon.getText();
        String total = ttotal.getText();
        
        if (kd_paket.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Paket not valid");
            return true;
        } else if (!kd_paket.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Kode Paket not numberic");
            return true;
        }
        
        if (nama_pengiriman.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Pengirim not valid");
            return true;
        }
        
        if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat not valid");
            return true;
        }
        
        if (jml_paket.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Barang not valid");
            return true;
        }
        
        return false;
        
        }

    private void kosong() {
       tkode.setText(null);
       tnama.setText(null);
       talamat.setText(null);
       tjml.setText(null);
       tjml.setText(null);
       tbiaya.setText(null);
       tdiskon.setText(null);
       ttotal.setText(null);       
    }
}
